### ISSUE TITLE
Suggestion about the organisation of the repository

### ISSUE THREAD

**Issue by FlowArg** [danieldieeins/OpenLauncherAPI#1]
Hallo!
I've discovered this project with the notification of the forks of some of my repositories, and thank you for your interest in some of my projects.
It's relevant to create this kind of project to simplify the process of making a Minecraft launcher (although it's very simple these days!).
But, there are some issues in your repository.
The big one is: you put all the code directly in the repository. It's not very suitable and a nightmare to maintain in the future, especially to update them. You really should consider use the libraries via a Maven dependency. They all are published on either Maven Central or a custom repository (OpenAuth).
I also didn't understand the point of forking some projects to archive them instantly.
You can also use the git references to refer to a code from another repository (like [Waterfall](https://github.com/PaperMC/Waterfall) does with BungeeCord)

If you wish/need to modify something in FlowUpdater, we can discuss it by DM on Discord (flowarg) / on GitHub as you wish.
++

**Comment by danieldieeins** [comment]
Hey Flow!
Thank you for your report. This project is the first thing I manage directly from Github, so I don't really know the features of the platform yet, hence the forks that were archived directly.
The biggest reason why I merged the projects here is mainly to only have to update one project and here I made all projects compatible with Java 17 and higher since they were previously limited to Java 8 by gradle (thats like i understood your READMEs ).

I also find it much easier if you only have to import one project instead of four. I'm currently working at full speed on new updates to offer a really easy way for everyone to create launchers with the API over time.

However, if you want me to remove your projects, I will either try to rewrite all the code myself for the next update, or archive/delete this project. There are those two possibilities for me because that bundled thing is the point of the project.

**Comment by FlowArg** [comment]
> compatible with Java 17 and higher since they were previously limited to Java 8 by gradle (thats like i understood your READMEs ).

Not really, these libs work for all version of Java starting of 8. To keep this range of compatibility, I've to keep building the project with Java 8. But it works perfectly with Java 17!


> I also find it much easier if you only have to import one project instead of four

It was never a problem: today's tools like Gradle or Maven are very powerful and in one line we can use a project as dependency. To update them is just changing a number in the build tool configuration file, easier, cleaner and more conventional than cloning some code from a repository.


> However, if you want me to remove your projects, I will either try to rewrite all the code myself for the next update, or archive/delete this project. There are those two possibilities for me because that bundled thing is the point of the project.

It really depends on your goal. If it's to provide some abstraction/easier way to create a launcher, you don't need to merge the code because you can just use it as a dependency. Your project could also be a template to create a launcher with z.b. a predefined design that can be customisable etc...
